### ISSUE TITLE
Cannot finish compilation with INTERFACE=1

### ISSUE THREAD

**Issue by hecmay** [OCT-FPGA/udp-network-demo#2]
This is a weird issue. I was able to compile with INTERFACE=3 into a working bitstream. and I am trying to run the compilation with `INTERFACE=1` to verify if the INTERFACE1 is actually working on its own (#1), but the synthesis process is suspended there forever... 

```bash
# .....
# ..... It has been stuck at block level synthesis for almost 20 hours...
[14:33:49] Block-level synthesis in progress, 46 of 47 jobs complete, 1 job running.
[14:34:19] Block-level synthesis in progress, 46 of 47 jobs complete, 1 job running.
```

Vitis version is 2021.2. Not sure if this is the cause (as the README says that version 2020 should be used, but I cannot find 2020 on the build server)

**Comment by surangamh** [comment]
This is probably because the VM doesn't have enough memory. This can happen when multiple users run their builds simultaneously. Use /proc/meminfo or htop to check the available RAM. We are currently working on setting up the build workflow in CloudLab, and we expect it to be ready for use in the next few weeks. You won't run into this issue then.

**Comment by surangamh** [comment]
Closing as you no longer have this issue.
